// automatically generated by the FlatBuffers compiler, do not modify

package Game;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class GameMessage extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static GameMessage getRootAsGameMessage(ByteBuffer _bb) { return getRootAsGameMessage(_bb, new GameMessage()); }
  public static GameMessage getRootAsGameMessage(ByteBuffer _bb, GameMessage obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public GameMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte dataTypeType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public Table dataType(Table obj) { int o = __offset(6); return o != 0 ? __union(obj, o + bb_pos) : null; }

  public static int createGameMessage(FlatBufferBuilder builder,
      byte dataTypeType,
      int dataTypeOffset) {
    builder.startTable(2);
    GameMessage.addDataType(builder, dataTypeOffset);
    GameMessage.addDataTypeType(builder, dataTypeType);
    return GameMessage.endGameMessage(builder);
  }

  public static void startGameMessage(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addDataTypeType(FlatBufferBuilder builder, byte dataTypeType) { builder.addByte(0, dataTypeType, 0); }
  public static void addDataType(FlatBufferBuilder builder, int dataTypeOffset) { builder.addOffset(1, dataTypeOffset, 0); }
  public static int endGameMessage(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishGameMessageBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedGameMessageBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public GameMessage get(int j) { return get(new GameMessage(), j); }
    public GameMessage get(GameMessage obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

