// automatically generated by the FlatBuffers compiler, do not modify

package Game;

@SuppressWarnings("unused")
public final class GameData {
  private GameData() { }
  public static final byte NONE = 0;
  public static final byte ServerMessage = 1;
  public static final byte ClientMessage = 2;

  public static final String[] names = { "NONE", "ServerMessage", "ClientMessage", };

  public static String name(int e) { return names[e]; }
}

